GA - Python Programming/venvs/lesson8/dashboard/dashboard/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('forms/', views.form_view, name="form_view"),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:slug>/',views.blog_view,name="blog_view"),
    path('homeworks/', views.homeworks_view, name="homeworks_view"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

GA - Python Programming/venvs/lesson8/dashboard/dashboard/forms.py
from django import forms

NEWSLETTER_CHOICES = [
    ['all', 'I want it all'],
    ['important', 'I want only important'],
]

AGE_CHOICES = [
    [0, '0-18'],
    [19, '19-39'],
    [40, '40-59'],
    [60, '60+'],
]


class MyForm(forms.Form):
    email = forms.EmailField(max_length=1024)
    password = forms.CharField(max_length=1024, widget=forms.PasswordInput)
    remember_me = forms.BooleanField(required=False)
    newsletter = forms.ChoiceField(
        choices=NEWSLETTER_CHOICES,
        widget=forms.RadioSelect,
    )
    age = forms.ChoiceField(choices=AGE_CHOICES)
    remarks = forms.CharField(required=False, widget=forms.Textarea)

    def clean_remarks(self):
        data = self.cleaned_data.get('remarks')
        if len(data) < 10:
            raise forms.ValidationError('Please enter at least 10 characters')
        return data

GA - Python Programming/venvs/lesson8/dashboard/dashboard/views.py
from decimal import Decimal
import os
import psutil
import csv

from django.shortcuts import render


def home_view(request):
    memory = psutil.virtual_memory().percent
    cpu = psutil.cpu_percent()
    hdd = psutil.disk_usage('/').free / 1024 / 1024 / 1024
    csv_data = []
    with open('data.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            csv_data.append(row)


    chart_title = 'Recycling Rate'
    chart_labels = []
    chart_data = []
    waste_type = request.GET.get('waste_type', 'Plastics')
    for row in csv_data:
        if row['waste_type'] == waste_type:
            chart_labels.append(row['year'])
            chart_data.append(row['recycling_rate'])

 # new code
    from datetime import datetime
    filename = request.POST.get('filename')
    change_time = None
    if filename:
        change_time = datetime.fromtimestamp(os.path.getmtime(filename))

    ctx = {
        'filename': filename,
        'change_time': change_time,
        # end of new code
        'memory': memory,
        'cpu': cpu,
        'hdd': hdd,
        'csv_data': csv_data,
        'chart_title': chart_title,
        'chart_labels': chart_labels,
        'chart_data': chart_data,
    }

    return render(request, 'home_view.html', ctx)

def homeworks_view(request):
    card_titles = [
        'Card 1',
        'Card 2',
        'Card 3',
        'Card 4',
        'Card 5',
        'Card 6',
        'Card 7',
        'Card 8',
        'Card 9',
        'Card 10',
    ]
    data = [('2001', 1), ('2002', 3), ('2003', 2), ('2004', 5), ('2005', 2)]
    ctx = {'card_titles': card_titles, 'data': data}
    return render(request, 'homeworks_view.html', ctx)

def blog_view(request, year, month, day, slug):
    ctx = {
        'year': year,
        'month': month,
        'day': day,
        'slug': slug,
    }
    return render(request, 'blog_view.html', ctx)
    
from .forms import MyForm
def form_view(request):
    print(request.POST)

    form = MyForm()

    if request.method == 'POST':
        form = MyForm(data=request.POST)
        form.is_valid()

    ctx = {'form': form}

    return render(request, 'form_view.html', ctx)

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "styles.css" %}">

  {% block title %}{% endblock %}

</head>

<body>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"
    integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
  <div class="flex-row">
    <div class="sidebar">
      <a class="sidebar-link" href="#">
        <i class="fa fa-tachometer"></i>
        <span class="d-none d-md-inline"> Home</span>
      </a>
      <!-- new code starts here -->
      <br /><br />
      <a class="sidebar-link" href="/forms/">
        <i class="fa fa-list-alt"></i><span class="d-none d-md-inline">Forms</span>
      </a>
      <!-- new code ends here -->
    </div>
    <div class="main-window">
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/blog_view.html
{% extends "base.html" %}

{% block content %}

<div class="card col-12 col-xl-6">
    <h1>{{ slug }}</h1>
    <p>{{ year }}-{{ month }}-{{ day }}</p>
    <hr />
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua.
    </p>
</div>

{% endblock %}

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/form_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Form View</h1>
<form method="POST" action=".">
  {% csrf_token %}
  {% comment %}
    {{ form.as_p }}
  {% endcomment %}
  {{ form|crispy }}
  <button type="submit">Submit</button>
  {% comment %}
    {{ form.errors }}
  {% endcomment %}
</form>

<hr />

{% comment %}
    <p>
        <label for="id_email">Email</label>
        <input type="text" id="id_email" name="email" placeholder="Your Email..." />
    </p>
    <p>
        <label for="id_password">Password</label>
        <input type="password" id="id_password" name="password" placeholder="Your Password..." />
    </p>
    <p>
        <input type="checkbox" id="id_remember_me" name="remember_me" value="yes" />
        <label for="id_remember_me">Remember me</label>
    </p>
    <p>
        <input type="radio" id="id_newsletter_1" name="newsletter" value="all" />
        <label for="id_newsletter_1">I want all newsletters</label>
        <br />
        <input type="radio" id="id_newsletter_2" name="newsletter" value="important" />
        <label for="id_newsletter_2">I want only important announcements</label>
    </p>
    <p>
        <label for="id_date">Date</label>
       <input type="date" id="id_date" name="date" />
    </p>
    <p>
        <label for="id_age">Age</label>
        <select id="id_age" name="age">
            <option value="">-----</option>
            <option value="0">0-18</option>
            <option value="19">19-39</option>
            <option value="40">40-59</option>
            <option value="60">60+</option>
        </select>
    </p>
    <p>
        <label for="id_remarks">Remarks</label><br />
        <textarea id="id_remarks" name="remarks" placeholder="Your remarks..."></textarea>
    </p>
     <button type="submit">Submit</button>
</form>
{% endcomment %}


{% endblock %}

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/home_view.html
{% extends "base.html" %}

{% block title %}
<title>Home|Dashboard</title>
{% endblock %}

{% block content %}
<h1>Dashboard</h1>

<div class="row row-cols-1 row-cols-md-3">
  <div class="col mb-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Memory</h5>
        <p class="card-text">{{ memory }}%</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">CPU</h5>
        <p class="card-text">{{ cpu }}%</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Disk Free</h5>
        <p class="card-text">{{ hdd |floatformat:"2" }} GB</p>
      </div>
    </div>
  </div>
    <!-- This is the new code -->
  <div class="col mb-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">File Change Time</h5>
        <form method="POST" action=".">
          {% csrf_token %}
          <input type="text" name="filename" placeholder="filename" value="{{ filename }}" />
          <button>Submit</button>
        </form>
        {% if filename %}
        <hr />
        <p>{{ filename }}: {{ change_time }}</p>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- End of new code -->
</div>

<div class="row row-cols-1 row-cols-md-2">
  <div class="col mb-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">CSV Chart</h5>
        {% include "partials/csv_chart.html" %}
      </div>
    </div>
  </div>

  <div class="col mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">CSV Table</h5>
        <div style="overflow-y: scroll; height: 300px;">
          {% include "partials/csv_table.html" %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/homeworks_view.html
{% extends "base.html" %}

{% block title %}
<title>Homeworks|Dashboard</title>
{% endblock %}

{% block content %}

<h1>Homeworks</h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
    {% for key in card_titles %}
        <div class="col mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title">{{ key }}</h5>
            </div>
          </div>
        </div>
    {% endfor %}
</div>

<div class="card h-100">
  <div class="table-responsive">
    <table class="table table-sm table-bordered table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">"Year"</th>
          <th scope="col">"Value"</th>
        </tr>
      </thead>
      <tbody>
       {% for row in data %}
          <tr>
            <td scope="row">{{ row.0 }}</td>
            <td>{{ row.1 }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/partials/csv_chart.html
<canvas id="myChart" width="100%"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: {{ chart_labels|safe }},
        datasets: [{
            label: '{{ chart_title }}',
            data: {{ chart_data|safe }},
            borderColor: 'rgb(28.3%, 84.3%, 96.8%)',
            backgroundColor: 'rgb(64.6%, 86.1%, 90.9%)',
            pointBorderColor: 'rgb(28.4%, 63.7%, 71.4%)',
            pointBackgroundColor: 'rgb(28.4%, 63.7%, 71.4%)',
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

GA - Python Programming/venvs/lesson8/dashboard/dashboard/templates/partials/csv_table.html
<div class="table-responsive">
  <table class="table table-sm table-bordered table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        {% for key in csv_data.0.keys %}
        <th scope="col">{{ key }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for row in csv_data %}
      <tr>
        <th scope="row">{{ row.year }}</th>
        <th><a href="./?waste_type={{ row.waste_type }}" style="color: inherit;">{{ row.waste_type }}</a></th>
        <th>{{ row.recycling_rate }}</th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>